CREATE WAREHOUSE IF NOT EXISTS VHOL_TASK_WAREHOUSE_STAGING;

ALTER WAREHOUSE VHOL_TASK_WAREHOUSE_STAGING
  SET
  WAREHOUSE_SIZE = XSMALL
  AUTO_RESUME = TRUE
  AUTO_SUSPEND = 1
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Task warehouse for STAGING environment';