GRANT USAGE ON DATABASE ${DATABASE} TO ROLE STAGING_READER;
GRANT USAGE ON SCHEMA ${DATABASE}.CORE TO ROLE STAGING_READER;

GRANT SELECT
  ON FUTURE TABLES IN SCHEMA ${DATABASE}.CORE
  TO ROLE STAGING_READER;
``