GRANT USAGE ON DATABASE GIT_DEMO_STAGING TO ROLE STAGING_READER;
GRANT USAGE ON SCHEMA GIT_DEMO_STAGING.CORE TO ROLE STAGING_READER;

GRANT SELECT
  ON FUTURE TABLES IN SCHEMA GIT_DEMO_STAGING.CORE
  TO ROLE STAGING_READER;
